### ISSUE TITLE
Is that possible to call functions in home.js from <iframe>?

### ISSUE THREAD

**Issue by chilejiang1024** [OfficeDev/Word-Add-in-DocumentAssembly#10]
I have some pages, and use them in my word add-in, by <iframe>. 

But I can not call functions in home.js from my pages.

These are the codes in my pages : 

    window.parent.test();

and codes in home.js :
   
    function test() {
        console.log('It's worked!');
    }

**Comment by lindalu-MSFT** [comment]
Closing all issues since this repo is being archived and no longer maintained.
