### ISSUE TITLE
Error while running from word online

### ISSUE THREAD

**Issue by sumansaha15** [OfficeDev/Word-Add-in-DocumentAssembly#2]
Hi,

When I am trying to run this add-in from browser as word online document, it is throwing error that the browser does not support this. Here is the full error - 
ErrorCode = GeneralException, ErrorMessage = This browser does not support the requested API.

Does this or overall office fabric not support word online?

Thanks!
Suman

**Comment by JuaneloJuanelo** [comment]
Thats because the APIs that are used in this sample are not yet supported on Word Online, by mid -april they should be avialable. thanks!

**Comment by jthake** [comment]
Should the smaple not defend against that and check the office host and handle it?

**Comment by JuaneloJuanelo** [comment]
yes it can use the isSetSupported method to do runtime verifications. (will update it soon, but feel free to fork and add the verifications)

its of the shape:

  if (Office.context.requirements.isSetSupported("WordApi", "1.1")) {
       //do whatever you need its supported
            })
            .catch(function (myError) {
                //otherwise we handle the exception here!
                showNotification("Error", myError.message);
            })
        }
        else {
            showNotification("Error. This functionality its not supported in your version of Word");
        }
    }
