### ISSUE TITLE
Append and not replace

### ISSUE THREAD

**Issue by SilverSnake83** [OfficeDev/Word-Add-in-DocumentAssembly#9]
Hi

On this example you show how to put content of a XML by using the setSelectedDataAsync to insert the content. 
But is there a way to put content many times without replacing the current selection?
To be more clear is there a way to unselect the content we put by using setSelectedDataAsync ?

**Comment by JuaneloJuanelo** [comment]
Hello. Thanks for asking the question. Absolutely that is possible to do, but you need to use the latest APIs for this. check out the range.insertOoxml method. it accept 2 parameters, the OOXML you want to insert, and the insert location.  The second parameter supports start, end, after, before and replace.  If you use any of the options other than replace you will insert the content in such locations. Chek out the documentation and a sample on this page: https://dev.office.com/reference/add-ins/word/range#insertooxmlooxml-string-insertlocation-insertlocation

**Comment by SilverSnake83** [comment]
Yes thank you for your answer. I figured this out but didn't mention it here sorry.
Thank's again!
